---
kind: pipeline
name: EpicHook CI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: ubuntu:20.04
    environment:
      GIT_ID:
        from_secret: GITID
      GIT_PWD:
        from_secret: GITPWD
    commands:
      - cd /drone/src
      - apt update && apt install -y bc bison curl flex gcc git g++ libssl-dev liblz4-1 libyaml-0-2 make p7zip-full zip zipalign
      - git clone https://github.com/arter97/arm64-gcc build-tools/arm64-gcc --depth 1
      - git clone https://github.com/arter97/arm32-gcc build-tools/arm32-gcc --depth 1
      - git clone https://$GIT_ID:$GIT_PWD@github.com/rsyhan/priv_Flyme_sm6150 -b bisect kernel --depth 1
      - bash ./build.sh
