---
kind: pipeline
name: EpicHook CI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: ubuntu:20.04
    environment:
      GIT_ID:
        from_secret: GITID
      GIT_PWD:
        from_secret: GITPWD
    commands:
      - cd /drone/src
      - apt update && apt install -y curl git
      - git clone https://github.com/MiCode/Xiaomi_Kernel_OpenSource -b cas-q-oss
      - cd Xiaomi_Kernel_OpenSource
      - git push https://$GIT_ID:GIT_PWD@github.com/rsyhan/android_kernel_xiaomi_sm8250 HEAD:cas-q-oss
     
